### ISSUE TITLE
I think it isn't supposed to do what it does lol

### ISSUE THREAD

**Issue by EnisGithub** [HomelessPhD/Wealth_in_Poetry#1]
Ok so basically the script generates exactly 511 combinations every time and after that it just displays a few Wallet addresses and after that just some words without context (every time the same output of the program, idk why) just wanted to tell you.

**Comment by HomelessPhD** [comment]
Thats correct, since it process the same file "text.txt". Change the file -
you will get different result. The last 12 words lists you see - are
mnemonics generated from the text that have valid checksum (and the
addresses for this mnemonic is given above the mnemonic)

**Comment by HomelessPhD** [comment]
Anyway, i've edited the script to output the pairs of "BTC address: mnemonics" to the console and the message whether the address of interest (the puzzle reward) has been found (the incorrect in sense of checksume mnemonics is still printed but in the log file).

I am open to ideas. By the way, numbers in article could have some meaning (like the examples the author shown us in the article), private keys are actuallly could be constructed from seed-words with bad checksum (so may be i should try to use the incorrect mnemonics too), amount of seed words could be different form 12 (yeah, the author shown us 12 word seed in example, but it could 24 words as well or even something in the middle like 15 words etc.), it could be even not a seed words at all - maybe we should take some characters from text and form the private key.
